name: vote Reply

'on':
  - workflow_dispatch

jobs:
  remove_labels_when_done:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        if: github.event.project_card.column_id == '18384090' # 已完成
        uses: andymckay/labeler@master
        with:
          add-labels: "vote"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: vote
        if: github.event.label.name == 'vote'
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            请您为开往的发展投票（https://github.com/travellings-link/travellings/discussions/1061）
